# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'OdeumKopsas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AlamofireRSSParser"

  # Pods for OdeumKopsas

  target 'OdeumKopsasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OdeumKopsasUITests' do
    # Pods for testing
  end

end
